import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less']
})
export class AppComponent {
  title = 'babel-box-front';

  test = JSON.parse(`{"from":"en","to":"fr","originalTerm":"word","pronunciation":"'word', 'Word': 'wɜːd","results":[{"signification":"mot","originalExample":"This sentence has five words.","translatedExample":"Cette phrase a cinq mots."},{"signification":"parole","originalExample":"He gave his word that he would fix the problem by Friday.","translatedExample":"Il lui donna sa parole qu'il arrangerait le problème avant vendredi."},{"signification":"formuler","originalExample":"You should word it differently so he doesn't get upset.","translatedExample":"Tu devrais formuler ça différemment pour ne pas le vexer."},{"signification":"mots","originalExample":"They exchanged words, and he left very upset.","translatedExample":"Ils eurent des mots, après quoi il partit vexé."},{"signification":"mots","originalExample":"Words are not enough. You have to do something about it.","translatedExample":"Les mots ne suffisent pas. Tu dois réagir."},{"signification":"paroles","originalExample":"Have you listened closely to the words of this song?","translatedExample":"Est-ce que vous avez écouté attentivement les paroles de cette chanson ?"},{"signification":"bruit","originalExample":"Did you hear the word about Jack and Jill?","translatedExample":"Tu as entendu le bruit qui court sur Jack et Jill ?"},{"signification":"nouvelle","originalExample":"Have you heard any word from your brother lately?","translatedExample":"As-tu eu des nouvelles de ton frère récemment ?"},{"signification":"mot","originalExample":"Let me go have a word with him about the loud music.","translatedExample":"Laisse-moi lui dire un mot à propos du volume de la musique."},{"signification":"ordre","originalExample":"You better follow your father's words.","translatedExample":"Tu ferais mieux de suivre les ordres de ton père."},{"signification":"mot de passe","originalExample":"You need to give the word, or we cannot open the door for you.","translatedExample":"Tu dois nous donner le mot de passe sinon nous ne pouvons pas t'ouvrir la porte."},{"signification":"parole","originalExample":"You can read the Word of God in the Bible.","translatedExample":"Tu peux lire la parole de Dieu dans la bible."},{"signification":"évangile","originalExample":"That is the Word according to John.","translatedExample":"Ceci est l'évangile selon saint Jean."},{"signification":"paroles","originalExample":"The doctor's words failed to comfort her.","translatedExample":"Les paroles du médecin ne purent la réconforter."}]}`);
}
